<a href="https://colab.research.google.com/github/deepakk7195/IISC_CDS_DS/blob/python_universe/python_concepts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# conda install -c nvidia -c rapidsai -c numba -c conda-forge -c defaults cudf
# !pip install cudf-cu11==22.12 rmm-cu11==22.12 dask-cudf-cu11==22.12 --extra-index-url=https://pypi.ngc.nvidia.com/

In [27]:
# %load_ext cudf.pandas
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import json
pd.pandas.set_option('display.max_columns',None)
import time
from datetime import datetime
import sympy as sym   # Solving Calculus, Limits,
import matplotlib.pyplot as plt
# import tnrange
# import tqdm_notebook
# import nb_black -> Automatic code formatter?

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import os
drive_folder = '/content/drive/MyDrive/Colab Notebooks/IISC_CDS/Python'
os.chdir(drive_folder)

## Basics - List, Array, Strings

### Popular methods -
- append - Entire string is added ||| adds one element to the end of the list.
- extend - String added charcter by character individually ||| adds multiple elements to the end of the list, with those elements individually added to the list
- insert - Given value at given index -> insert(index,value)
- pop - deleting a value
- count(value) - Counts Occurances
- lst.sort() just sorts the list in place returning None but sorted(lst) returns sorted list
- c_lst = o_lst  copy by reference & c_lst = o_lst.copy()  copy by value
- + => Concatenation -> [1,2,3] + [2],[1,2,3] + ['A','B']
in statement - if i in lst
any() - Only through Generator expression => any(item in test_list for item in test_list) ??
find() - Usually in strings, to search a substring & return index of 1st value of the substring in main string.
counter() -
list.index(value)

In [ ]:
nums = [2,3,4,5,6,9] # len = 5
nums2 = [6,7,5,456,34,4]
num = nums+nums2
# print(nums*nums2) #NOT POSSIBLE here in list but possible in numpy array
for i in range(len(nums)):
    print(i,nums[i],len(nums),end = ' ')
# for i in range(len(nums)):
#     print(nums[i],end = ' ')
# nums.sum() - Not supported unlike for numpy arrays
sum(nums)
# count(nums) # Not Supported

In [ ]:
nums[0:-1]  #[2, 3, 4, 5, 6]
nums[:-1]#[2, 3, 4, 5, 6]
nums[0:1]
nums.count(4)
nums.insert(5,4)
nums.find([4,5,6]) # XX - Can't use on list

In [ ]:
my_string = "Python is a popular programming language"
substring = "popular"
index = my_string.find(substring)
if index != -1:
    print(f"The substring '{substring}' was found at index {index}")
else:
    print(f"The substring '{substring}' was not found in the string.")

The substring 'popular' was found at index 12


In [ ]:
import numpy as np
ar=np.array([1,0,0,1])
arr2=np.array([1,0,0,0])
arr3=np.array([0,0,0,0])

In [ ]:
# Calculate the sum of the elements in the diagonal of a following matrix / 2D array, and logic
# should be dynamic enough to work on any NxN matrix
# 1  2  3
# 4  5  6
# 7  8  9
# sum1 = 1 + 5 + 9
# sum2 = 3 + 5 + 7
def sum_diag(matrix):
    if not matrix:
        return 0
    main_diag_sum = sum(matrix[i][i] for i in range(len(matrix)))
    cross_diag_sum = sum(matrix[i][len(matrix)-i-1] for i in range(len(matrix)))
    return main_diag_sum,cross_diag_sum
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print("List Matrix - ",matrix)
arr = np.array(matrix)
print("Numpy Array - ",arr)
main_diagonal_sum, other_diagonal_sum = sum_diag(matrix)
print(f"Sum of the main diagonal: {main_diagonal_sum}")
print(f"Sum of the other diagonal: {other_diagonal_sum}")

List Matrix -  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Numpy Array -  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of the main diagonal: 15
Sum of the other diagonal: 15


In [ ]:
dcd=np.array([1,0,0,1])
print(dcd,type(dcd))
jhdsbcd = np.array([dcd])
print(jhdsbcd,type(jhdsbcd))

[1 0 0 1] <class 'numpy.ndarray'>
[[1 0 0 1]] <class 'numpy.ndarray'>


In [ ]:
for i in range(0,3):
    tl_vec=np.array([1,0,0,i])
    if i==0:
        tlmat = np.array([tl_vec])
    else:
        tlmat = np.vstack([tlmat,tl_vec])
print(type(tlmat))
tlmat

<class 'numpy.ndarray'>


array([[1, 0, 0, 0],
       [1, 0, 0, 1],
       [1, 0, 0, 2]])

In [ ]:
if len(tlmat)>0:
    plmat = list(tlmat.sum(axis=0))
print("PLMAT = ",plmat)
PROL_RULES = ["prolrule1","prolrule2","prolrule3","prolrule4"]
result = {PROL_RULES[i]:plmat[i] for i in range(len(PROL_RULES))} # Forming a dictionary:Length of both lists must be same otherwise list index
#out of range
print("1st - ",result)
result2 = {PROL_RULES[i]:plmat[i] for i in range(len(plmat))}
print("2nd - ",result2)

PLMAT =  [3, 0, 0, 3]
1st -  {'prolrule1': 3, 'prolrule2': 0, 'prolrule3': 0, 'prolrule4': 3}
2nd -  {'prolrule1': 3, 'prolrule2': 0, 'prolrule3': 0, 'prolrule4': 3}


#### Numpy Array Matrix Properties Vs List array properties -
1. Data Type Homogeneity:
Lists can contain elements of mixed data types.
NumPy arrays are homogeneous; they contain elements of the same data type.
2. Element-Wise Operations:
Lists do not inherently support element-wise operations (e.g., division or multiplication. Addition supported).
NumPy arrays support element-wise operations.
3. Size and Shape Flexibility:
Lists can have varying sizes and shapes within a nested structure.
NumPy arrays have fixed sizes and shapes once created.
Ex. my_list = [[1, 2], [3, 4, 5], [6]] but not possible with array
4. Performance:
Lists <<< numerical computations <<< NumPy arrays.
NumPy arrays are optimized for performance.
5. Built-in Functions:
Lists have basic built-in functions.
NumPy arrays provide a wide range of mathematical and array manipulation functions. Aggregation
6. Slicing and Indexing:
Lists support basic slicing and indexing.
NumPy arrays support advanced slicing and indexing, including boolean indexing
result = my_array[my_array > 2]

In [ ]:
# Range Funciton -
a = [5,2,3,8,6,1,0,9] # size=8
# for i in range(len(a)): #range(3) generates 0,1,2
#     print(i,a[i])
# for i in a:
#     print(i)
for i in range(0,len(a)):
    print(i,a[i])

0 5
1 2
2 3
3 8
4 6
5 1
6 0
7 9


In [ ]:
myarr = [4,6,3,4,7,2,233,64]
myarr.count(myarr[3])

2

In [ ]:
myarr = [4,6,3,4,7,2,233,64]
for val in myarr:
    print("val - ",val) # iterate by value
for i in range(len(myarr)):
    print("val - ",myarr[i]) # iterate by value
for i in range(len(myarr)):
    print("index - ",i) # iterate by index
for idx,val in enumerate(myarr):
    print("idx-val - ",idx,val) # iterate by both
for idx,val in enumerate(range(len(myarr))):
    print("range idx-val - ",idx,val) # iterating by both but here val is also idx, thus non sense
# for idx,val in enumerate(len(myarr)):
#     print("idx-val - ",idx,val) # Wrong
# for i in myarr[i]:
#     print(i) # IndexError: list index out of range

In [ ]:
#Q.1 Funciton to flatten a nested list -
def flatten(lst):
    result = []
    for i in lst:
        if isinstance(i, list):
            result.extend(flatten(i))
        else:
            result.append(i)
    return result

nested_list = [1, [2, 3, [4, 5]], 6]
print(flatten(nested_list))  # Output: [1, 2, 3, 4, 5, 6]

[1, 2, 3, 4, 5, 6]


In [ ]:
# Q.2 Counting frequency of chars in a string -
inputstr = "Hello World"
freq = {}
for i in inputstr:
	if i in freq:
		freq[i] = freq[i]+1
	else:
		freq[i] = 1
print(freq)

{'H': 1, 'e': 1, 'l': 3, 'o': 2, ' ': 1, 'W': 1, 'r': 1, 'd': 1}


In [ ]:
# Q.2 Alternate -
counts = dict()
names = ['steve', 'mark', 'steve', 'zhen', 'mark'] #These are keys of counts
#names = "Hello World"
for name in names:
#     print(counts.get(name, 0))
    counts[name] = counts.get(name,0)+1 # '0' is default
print(counts)

{'steve': 2, 'mark': 2, 'zhen': 1}


In [ ]:
#Q.3] Most repeated character in a string,list using with/without enumerate -
def most_repeated(s):
    char_count = {}
    for char in s:
        if char in char_count:
            char_count[char] += 1
        else:
            char_count[char] = 1
    max_char = max(char_count, key=char_count.get) #.get method of a dictionary to get value
    print("key-",char_count.get)
    print("char_count = ",char_count)
    return max_char
string = "aabbbcdddde"
print("Output - ",most_repeated(string))

key- <built-in method get of dict object at 0x7f1968f47bc0>
char_count =  {'a': 2, 'b': 3, 'c': 1, 'd': 4, 'e': 1}
Output -  d


In [ ]:
# Q.4]
def find_common_elements(list1, list2):
    common_elements = []
    for item in list1:
        if item in list2:
            common_elements.append(item)
    return common_elements
def find_common_elements(list1, list2):
    set1 = set(list1)
    set2 = set(list2)
    common_elements = list(set1.intersection(set2))
    return common_elements

In [ ]:
# Q.5] Fibonacci -
#Write a function to compute the Fibonacci series up to n.
def fibonacci(n):
    series = [0, 1]
    while len(series) < n:
        series.append(series[-1] + series[-2])
    return series
number = 10
print(fibonacci(number))

# Fibonacci recursive -
def fibonacci(n):
    if n <= 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci(n - 1) + fibonacci(n - 2)
# Number of Fibonacci numbers to generate
n = 10
# Generate and print the first n Fibonacci numbers
for i in range(n):
    print(fibonacci(i), end=" ")
# In this program, the fibonacci function is defined recursively. It returns the n-th Fibonacci number.
# The base cases are when n is 0 or 1, in which the function returns 0 and 1, respectively.
# For larger values of n, the function recursively

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]
0 1 1 2 3 5 8 13 21 34 

In [ ]:
#Q.6]  If 2 Strings are in rotation-
def are_rotations(str1, str2):
    if len(str1) == len(str2):
        return False
    return str1 in str1 + str2
s1 = "abcde"
s2 = "cdeabiovhjsdabcde"
print("1 - ",are_rotations(s1, s2))
lst1 = [4,5,6,7,7,8]
lst2 = [7,8,4,5,6,7]
print("2 - ",are_rotations(lst1,lst2))
# WILL WORK FOR STRINGS BUT NOT FOR LISTS, AS STRINGS ARE IMMUTABLE UNLIKE LIST.

1 -  True
2 -  False


In [ ]:
#Q.7]   Child list in a parent list. Ordered or just all elements are present
#1. Orderly / Contiguous manner -
def is_sublist(sublist, parent_list):
    for i in range(len(parent_list) - len(sublist) + 1):
        if parent_list[i:i + len(sublist)] == sublist: # slicing list & checking if the slice is sublist
            return True
    return False

# Plain check -
def is_sublist(sublist, parent_list):
    return all(item in parent_list for item in sublist)

#Converting in Set -
def is_sublist(sublist, parent_list):
    return set(sublist).issubset(set(parent_list))

# Converting in String -
def is_sublist(sublist, parent_list):
    sublist_str = ''.join(map(str, sublist))
    parent_list_str = ''.join(map(str, parent_list))
    return sublist_str in parent_list_str

In [ ]:
sublist = [1,2,3,4]
parent_list = [1,2,3,4,5,6,7]
a = all(item in parent_list for item in sublist)
b = all(sublist[i]==parent_list[j] for i,j in enumerate(range(len(sublist))))
print(a)
print(b)

True
True


In [ ]:
#Q.8] If a string has all unique characters -
st1 = 'iugcfbdsjchsdiahds'
def has_unique_chars(s):
    return len(s) == len(set(s))
has_unique_chars(st1)

False

In [ ]:
#Q.9]  Move all 0s in a int list to the end -
def move_zeros(nums):
    count = nums.count(0)
    nums = [num for num in nums if num != 0]
    nums.extend([0] * count)
    return nums
numbers = [1, 2, 0, 4, 0, 5, 6, 0]
print(move_zeros(numbers))

[1, 2, 4, 5, 6, 0, 0, 0]


In [ ]:
a = '123'
i = len(a) - 2
n1 = int(a[i]) if i >= 0 else 0
print(n1)

2


In [ ]:
#Q.10] Write a function that returns the sum of two numbers represented as strings
def add_strings(num1, num2):
    res, carry, i, j = "", 0, len(num1) - 1, len(num2) - 1
    while i >= 0 or j >= 0 or carry:
        n1 = int(num1[i]) if i >= 0 else 0
        n2 = int(num2[j]) if j >= 0 else 0
        temp_sum = n1 + n2 + carry
        res = str(temp_sum % 10) + res
        carry = temp_sum // 10
        i, j = i - 1, j - 1
    return res
n1 = "123"
n2 = "789"
print(add_strings(n1, n2))

912


In [ ]:
#Q.11]  Returning grams out of ngrams -
tokens = ["my","name","is","deepak","khadke",".","I","am","from","jalgaon",""]
def ngrams(tokens,n):
    l = len(tokens)
    grams = [tokens[i:i+n] for i in range(l-n+1)]
    return grams
print(ngrams(tokens,3))
# Using generator instead of the list -
def gen_ngrams(tokens,n):
    l = len(tokens)
    for i in range(l-n+1):
        yield tokens[i:i+n]
ngrams_gen = gen_ngrams(tokens,3)
print(ngrams_gen)
print([i for i in ngrams_gen])
print(type(ngrams_gen))

##Higher Order Functions

In [ ]:
list(zip(range(5),range(3))) # Zipping Tuples. Not ind-val like dict. Happens only in dict object

[(0, 0), (1, 1), (2, 2)]

In [ ]:
dict(zip([1,2,3,4],[4,5,6]))

{1: 4, 2: 5, 3: 6}

In [ ]:
set(zip("hello",[1,2,3]))

{('e', 2), ('h', 1), ('l', 3)}

# Generator Comprehension - Round Brackets

In [ ]:
print((val for val in range(1, 20+1) if n % val == 0))

<generator object <genexpr> at 0x7f1d5aa55cb0>


##List Comprehension - Square Brackets

In [ ]:
lst = [i**2 for i in range(1,11)]
print(lst)
print(['E' if e %2 == 0 else 'O' for e in lst])
print(['P' if e > 0 else 'N' if e < 0 else 'Z' for e in lst])
print([(i,j,i*j) for i in range(1,6)  for j in range(1,7)])
response = [1,2,3,4]
plmat = list(np.zeros([2,len(response)])) # 1,2 is no of rows
print(plmat)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
['O', 'E', 'O', 'E', 'O', 'E', 'O', 'E', 'O', 'E']
['P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P']
[(1, 1, 1), (1, 2, 2), (1, 3, 3), (1, 4, 4), (1, 5, 5), (1, 6, 6), (2, 1, 2), (2, 2, 4), (2, 3, 6), (2, 4, 8), (2, 5, 10), (2, 6, 12), (3, 1, 3), (3, 2, 6), (3, 3, 9), (3, 4, 12), (3, 5, 15), (3, 6, 18), (4, 1, 4), (4, 2, 8), (4, 3, 12), (4, 4, 16), (4, 5, 20), (4, 6, 24), (5, 1, 5), (5, 2, 10), (5, 3, 15), (5, 4, 20), (5, 5, 25), (5, 6, 30)]
[array([0., 0., 0., 0.]), array([0., 0., 0., 0.])]


### Python Iterator, Generator & Decorator -
- generates a value (iterator object) on demand
- genrators are slower than list comprehension
- generators are memory efficient
- when to use: whenever, you need to do manipulation on set of values and return the output as a single value
- Iterable - An object that can be looped over, iterated over. Ex. List,set,tuples, dictionaries,strings. But, every iterable is not neccessarily be an iterator. But a list itself is not an iterator. Becomes after iter(), thus next() will work only after converting.
- Iterator => Obj that can be iterated upon. They contain countable no of values.
- Lazy Evaluation - Call by need
- Iterator Protocol
- next() - Built in function used to return next item in an iterator
- iter() - Convert an iterable into iterator
- yield() - when used in place of return in a def, it is a Generator
decorator is a design pattern and a function that allows you to modify or extend the behavior of callable objects  without permanently modifying their code

#Numpy
Inbulit methods => np.mean(), np.max(), np.min(), np.std(), np.sum(), np.cumsum(), np.reshape(), np.median(), np.where(), np.mod(), np.argmax(), etc.

In [ ]:
# Sample Input
# 1 2 3 4 5 6 7 8 9
# Sample Output
# [ [ 1 2 3 ]
# [ 4 5 6 ]
# [ 7 8 9 ] ]
import numpy
def arrays(arr):
    arr1 = numpy.array(arr, dtype = int)
    arr2 = arr1.reshape(3, 3)
    return arr2
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 5 6 7 89 9
[[ 1  2  3]
 [ 4  5  6]
 [ 7 89  9]]


In [ ]:
lst = [1, 2, 3, 1, 2, 3]
lst.sort()
print(lst)
print(sum(lst))

[1, 1, 2, 2, 3, 3]
12


In [ ]:
mystr = 'my name is deepak khadke'
s = mystr.split(" ")  # ['my', 'name', 'is', 'deepak', 'khadke']
s

['my', 'name', 'is', 'deepak', 'khadke']

In [ ]:
aaa = 'my name is deepak khadke 87236432'
bbb = ' '.join(aaa) # Do when each character needs to be separately presented.
print(bbb)
print(bbb[::-1])
print(bbb.split(" "))

m y   n a m e   i s   d e e p a k   k h a d k e   8 7 2 3 6 4 3 2
2 3 4 6 3 2 7 8   e k d a h k   k a p e e d   s i   e m a n   y m
['m', 'y', '', '', 'n', 'a', 'm', 'e', '', '', 'i', 's', '', '', 'd', 'e', 'e', 'p', 'a', 'k', '', '', 'k', 'h', 'a', 'd', 'k', 'e', '', '', '8', '7', '2', '3', '6', '4', '3', '2']


In [ ]:
sum([int(item) for item in input('Enter numbers: ').split(' ')])

Enter numbers: 1 2 3 4


10

#Tuple, Dictionary
1. Looping thro' = for kv in students.items(): ---------- Here tuple format. Key will be 1st element of the tuple and all values will be the 2nd element forming either a list or tuple again. Both elements will be separated by comma
2.  for k,v in students.items(): ------------------------------- Here no comma, Both Key Values appear in front of another
3. Students.keys(), students.values(), students.items()

In [ ]:
dictionary = {'Name': 'Tanu', 'Sex': 'Male', 'Age': 23, 'Height': 5.8, 'Occupation': 'Student'}
for i,j in dictionary.items():
    print("1 - ",i,i[0],j)
for i in dictionary.items():
    print("2 - ",i,i[0],i[1])

1 -  Name N Tanu
1 -  Sex S Male
1 -  Age A 23
1 -  Height H 5.8
1 -  Occupation O Student
2 -  ('Name', 'Tanu') Name Tanu
2 -  ('Sex', 'Male') Sex Male
2 -  ('Age', 23) Age 23
2 -  ('Height', 5.8) Height 5.8
2 -  ('Occupation', 'Student') Occupation Student


In [ ]:
## Very very basic -
keys = ['red', 'green', 'blue']
values = ['#FF0000','#008000', '#0000FF']
color_dictionary = dict(zip(keys, values))
print(color_dictionary)

# Converting into a DICTIONARY & dataframe -
group1 = [5, 7, 3, 4, 8]
group2 = [9, 12, 11, 13, 10]
group3 = [14, 16, 19, 17, 15]
data = {'Group 1': group1, 'Group 2': group2, 'Group 3': group3}
df = pd.DataFrame(data)

# Using zip -
group1 = [5, 7, 3, 4, 8]
group2 = [9, 12, 11, 13, 10]
group3 = [14, 16, 19, 17, 15]
data = list(zip(group1, group2, group3))
df = pd.DataFrame(data, columns=['Group 1', 'Group 2', 'Group 3'])

{'red': '#FF0000', 'green': '#008000', 'blue': '#0000FF'}


In [ ]:
# Q.12] Sorting the dictionary - DIFFERENFCE IN sort() & sorted() methods of LISTS
#By sort() -
keys = list(dictionary.keys())
keys.sort()
sorted_dict = {i: dictionary[i] for i in keys}
print(sorted_dict)
#By sorted() -
keyss = sorted(keys)
sorted_dict1 = {i: dictionary[i] for i in keyss}
print(sorted_dict1)

{'Age': 23, 'Height': 5.8, 'Name': 'Tanu', 'Occupation': 'Student', 'Sex': 'Male'}
{'Age': 23, 'Height': 5.8, 'Name': 'Tanu', 'Occupation': 'Student', 'Sex': 'Male'}


# Merging 2 Dictionaries-

# Python code to merge dict using update() method
1.  def Merge(dict1, dict2):
    return(dict2.update(dict1))
2. res = {**dict1, **dict2}
3. res = dict1 | dict2
4. for i in dict2.keys():
        dict1[i]=dict2[i]
5. merged_dict = dict(dict1.items() | dict2.items())
Write a Python function to merge two dictionaries. If both dictionaries have the same key, prefer the second dictionary's value.
def merge_dicts(dict1, dict2):
    merged = dict1.copy()
    merged.update(dict2)
    return merged

In [ ]:
#Q.13] Merging multiple -
dic1={1:10, 2:20}
dic2={3:30, 4:40}
dic3={5:50,6:60}
dic4 = {}
for d in (dic1, dic2, dic3): dic4.update(d)
print(dic4)

{1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}


In [ ]:
# Q.14] ITERATING IN JSON FILE : NESTED DICTIONARIES
country = {
    "country1": {
        "dept1": {"count": 50},
        "dept2": {"count": 20},
        "dept3": {"count": 5},
        "dept4": {"count": 55}
    },
    "country2": {
        "dept1": {"count":  50},
        "dept2": {"count": 20},
        "dept3": {},
        "dept4": {"count": 55}
    }
}

In [ ]:
count={}
for key,val in country.items():
    print(key,type(key))
    print(val)
    value=val
    for key1,val1 in value.items():
        if key1 in count:
            if len(val1)>0:
                count[key1]=count[key1]+val1['count']
        else:
            if len(val1)>0:
                count[key1]=val1['count']
print(count)

country1 <class 'str'>
{'dept1': {'count': 50}, 'dept2': {'count': 20}, 'dept3': {'count': 5}, 'dept4': {'count': 55}}
country2 <class 'str'>
{'dept1': {'count': 50}, 'dept2': {'count': 20}, 'dept3': {}, 'dept4': {'count': 55}}
{'dept1': 100, 'dept2': 40, 'dept3': 5, 'dept4': 110}


In [ ]:
#Q.15] combine two dictionary by adding values for common keys -
from collections import Counter
d1 = {'a': 100, 'b': 200, 'c':300}
d2 = {'a': 300, 'b': 200, 'd':400}
d = Counter(d1) + Counter(d2)
print(d)

Counter({'a': 400, 'b': 400, 'd': 400, 'c': 300})


In [ ]:
test_dict = {"Gfg": [5, 7, 5, 4, 5],
             "is": [6, 7, 4, 3, 3],
             "Best": [9, 9, 6, 5, 5]}
words = [i for i in test_dict.keys()]
val = [test_dict.get(i) for i in words]
print("VAL - ",val)
print(words)
for i in words:
    v = test_dict.get(i)
    print(v)

VAL -  [[5, 7, 5, 4, 5], [6, 7, 4, 3, 3], [9, 9, 6, 5, 5]]
['Gfg', 'is', 'Best']
[5, 7, 5, 4, 5]
[6, 7, 4, 3, 3]
[9, 9, 6, 5, 5]


In [ ]:
#Q.16]   Maximum no of Unique values -
unique_counts = [(key, len(set(values))) for key, values in test_dict.items()]
print(unique_counts)
maxval = 0
tp = ''
for tpl in unique_counts:
    if tpl[1] > maxval:
        maxval = tpl[1]
        tp = tpl
print(tp)

[('Gfg', 3), ('is', 4), ('Best', 3)]
('is', 4)


In [ ]:
data = {'1': ['a', 'b'], '2': ['c', 'd']}
list(data)

['1', '2']

In [ ]:
#Q.17]  create and display all combinations of letters, selecting each letter from a different key
# in a dictionary
data = {'1': ['a', 'b'], '2': ['c', 'd']}
lst = []
for i,v in enumerate(list(data)[:-1]):
    for letter1 in data[list(data)[i]]:
        for letter2 in data[list(data)[i+1]]:
            lst.append(letter1+letter2)
#             print("Loopwise Values - ",lst)
print("Final list - ",lst)

Final list -  ['ac', 'ad', 'bc', 'bd']


In [ ]:
counts = {'chunk' : 1, 'jeff' : 42, 'jan' : 100}
for key in counts:
    print(key, counts[key])
for i in counts:
    print(counts.get(i))

chunk 1
jeff 42
jan 100
1
42
100


In [ ]:
counts = dict()
print('Enter a line of text:')
line = input(' ')
words = line.split()
print('Words:', words) #list
print('Counting...')
for word in words:
    counts[word] = counts.get(word, 0) + 1
print('Counts', counts)

Enter a line of text:
 What does this code snippet do?
Words: ['What', 'does', 'this', 'code', 'snippet', 'do?']
Counting...
Counts {'What': 1, 'does': 1, 'this': 1, 'code': 1, 'snippet': 1, 'do?': 1}


In [ ]:
dict1 = {'chunk' : [45,3,4,'m','ok'], 'jeff' : 42, 'jan' : 100}
print(list(dict1))
print(list(dict1.keys())) # Both are equal.
print(list(dict1.values()))
print(list(dict1.items()))

['chunk', 'jeff', 'jan']
['chunk', 'jeff', 'jan']
[[45, 3, 4, 'm', 'ok'], 42, 100]
[('chunk', [45, 3, 4, 'm', 'ok']), ('jeff', 42), ('jan', 100)]


In [ ]:
#Q.37] Write a function to flatten a nested dictionary. Namespace the keys with a period.

def flatten_dictionary(d, parent_key='', sep='.'):
    items = {}
    for k, v in d.items():
        new_key = f"{parent_key}{sep}{k}" if parent_key else k
        if isinstance(v, dict):
            items.update(flatten_dictionary(v, new_key, sep=sep))
        else:
            items[new_key] = v
    return items

nested_dict = {
    "a": 1,
    "b": {
        "c": 2,
        "d": {
            "e": 3
        }
    }
}
print(flatten_dictionary(nested_dict))




# Group By Pandas
Group By -
1. By default, 2 default variables having names = group_name & group_data.
   PK -> group_name $ the corresponding data -> group_data.
2. .groups gives you all PKs in group_name. The object is not series or df but ->         pandas.io.formats.printing.PrettyDicty. Now we know that unlike list, dictionary is not ordered, thus it is neither directly subscriptable or callable, thus [0] won't work.
3. .keys() prints all PK as .groups becomes a Dictionary Object. What works is found below.
4. Understand list[] and list(). () is calling the list method and [] is used for indexing,slicing,accessing elements.
5. Group By object must be iterated to get the Keys & Values and convert into dictionary/dataframes.
6. Group By will preserve the order in which observations are sorted within each group
7. By default NA values are excluded from group keys during the groupby. Pass dropna=False to avoid.
8. In the case of grouping by multiple keys, the group name will be a tuple:
9. When you do Aggregation, keys of the groups appear in the index by default.

# Alt 1st element -
first_group_name = list(oo.groups.keys())[0]
first_group = oo.get_group(first_group_name)
first_group
# Getting a group by it's value -
grouped.get_group(value of the PK)
#Converting the object into dataframe
grouped_df = Experian_df.groupby('ID', as_index=False).apply(pd.DataFrame)

In [ ]:
# Convert GroupBy object to a dictionary
group_dict = {}
for group_name, group_data in oo:
    group_dict[group_name] = group_data.to_dict(orient='list')
# Into a list -
group_list = [group_data for group_name, group_data in Experian_df.groupby('group_column')]

pandas Index objects support duplicate values. If a non-unique index is used as the group key in a groupby operation, all values for the same index value will be considered to be in one group and thus the output of aggregation functions will only contain unique index values:

# HARD INTERVIEW Qs -

In [ ]:
#Q.18] Find index of 1st non repeating integer in the array -
# Can use dictionary to keep track of freq of each integer. Then iterate in array to find the 1st.
def first_nonrepeating_int(arr):
    freq_dict = {}
    for index, num in enumerate(arr):
        if num in freq_dict:
            freq_dict[num]+=1
        else:
            freq_dict[num]=1
    #Fetching the 1st -
    for index, num in enumerate(arr):
        if freq_dict[num]==1:
            return index,num
myarr = [4,345,2,2,6,54,32,32,9,89,0,222,42,44,222,22,222,22,6,7,9,3,2,3,7,67,12,6,9,9,31,223,4,2,12,12,2]
firstind,firstval = first_nonrepeating_int(myarr)
print(firstind,firstval)

1 345


In [ ]:
#Q.18] For string -
def first_non_repeated(s):
    char_count = {}
    for char in s:
        if char in char_count:
            char_count[char] += 1
        else:
            char_count[char] = 1
    for char in s:
        if char_count[char] == 1:
            return char,s.index(char)
string = "swiss"
print("Is this list - ",list(string))
print(type(list(string)))
print(first_non_repeated(string))

Is this list -  ['s', 'w', 'i', 's', 's']
<class 'list'>
('w', 1)


In [ ]:
#Q.19]: Rotate an array to the right by a given number of steps
def rotate_array(arr, k):
    n = len(arr) #5
    k = k % n
    return arr[-k:] + arr[:-k]
a = [1,2,3,4,5]
b = rotate_array(a,1)
b

[5, 1, 2, 3, 4]

In [ ]:
#Q.20]: Implement a binary search algorithm
def binary_search(arr, target):
    left, right = 0 , len(arr) - 1
    while left <= right:
        mid = (left + right) // 2
        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            left = mid + 1
        else:
            right = mid - 1
    return -1
a = [1,2,3,4,5,6]
binary_search(a,3)

2

In [ ]:
#Q.21]: Calculate the power of a number using recursion.
def power(x, n):
    if n == 0:
        return 1
    elif n % 2 == 0:
        return power(x, n // 2) ** 2
    else:
        return x * power(x, n - 1)
power(4,5)

1024

In [ ]:
#Q.22] Write a function to find the two numbers in a list that sum up to a specific target
def two_sum(nums, target):
    num_dict = {}
    for i, num in enumerate(nums):
        print(i,num)
        complement = target - num
        num_dict[num] = i
        if complement in num_dict:
            return [num_dict[complement], i]
    return None
numbers = [2,7,11,15,12,65,9,4,1,8,237,6,2,3,5,67,3,34,5,43,5,3,80,45,3536,3,6,3]
target_value = 67
print(two_sum(numbers, target_value))  # Output: [0, 1]

0 2
1 7
2 11
3 15
4 12
5 65
[0, 5]


In [ ]:
def get_appscore(phat) :
	log_odds = math.log(phat / (1 - phat))
	factor = 50 / math.log(2);
	offset = 600 - (factor * math.log(50))
	app_score = int(round(offset + (factor * log_odds), 0))
	return app_score

In [ ]:
# Calculating PSI of a data - *** Revisit Later *****
# Example dataset (replace this with your data)
data = pd.DataFrame({
    'Characteristic': ['Age', 'Income', 'Credit Score'],
    'Baseline': [30, 40, 700],
    'Current': [32, 42, 680]
})

# Define the number of bins for histograms
num_bins = 10

# Function to calculate PSI for a characteristic
def calculate_psi(baseline, current):
    # Create histograms for both populations
    baseline_hist, _ = np.histogram(baseline, bins=num_bins)
    current_hist, _ = np.histogram(current, bins=num_bins)
    # Calculate the percentage of each population in each bin
    p_baseline = baseline_hist / len(baseline)
    p_current = current_hist / len(current)

    # Handle cases where p_baseline or p_current is zero
    p_baseline = np.where(p_baseline == 0, 1e-10, p_baseline)
    p_current = np.where(p_current == 0, 1e-10, p_current)

    # Calculate the PSI value for the characteristic
    psi = np.sum((p_current - p_baseline) * np.log(p_current / p_baseline))

    return psi
# Calculate PSI for each characteristic
psi_values = []
for row in data.itertuples(index=False):
    psi = calculate_psi(list(row.Baseline), list(row.Current))
    psi_values.append(psi)

# Add PSI values to the dataset
data['PSI'] = psi_values

# Display the results
print("Characteristic Analysis Report:")
print(data[['Characteristic', 'PSI']])

In [ ]:
import numpy as np
predicted_probabilities = [0.1, 0.4, 0.6, 0.8, 0.3, 0.9]
true_labels = [0, 0, 1, 1, 0, 1]
data = list(zip(predicted_probabilities, true_labels))
print(data)
data_sorted = sorted(data, key=lambda x: x[0], reverse=True)
positives = [item[0] for item in data_sorted if item[1] == 1]
negatives = [item[0] for item in data_sorted if item[1] == 0]
print("1 - ",positives)
print("2 - ",negatives)
total_positives = sum(true_labels)
print("3 - ",total_positives)
total_negatives = len(true_labels) - total_positives
print("4 - ",total_negatives)
print("5 - ",np.cumsum(positives))
print("6 - ",np.cumsum(negatives))
cp_pos = np.cumsum(positives) / total_positives
cp_neg = np.cumsum(negatives) / total_negatives
print(cp_pos)
print(cp_neg)
ks = max(cp_pos - cp_neg)

[(0.1, 0), (0.4, 0), (0.6, 1), (0.8, 1), (0.3, 0), (0.9, 1)]
1 -  [0.9, 0.8, 0.6]
2 -  [0.4, 0.3, 0.1]
3 -  3
4 -  3
5 -  [0.9 1.7 2.3]
6 -  [0.4 0.7 0.8]
[0.3        0.56666667 0.76666667]
[0.13333333 0.23333333 0.26666667]


## Neetcodes's Leetcode Problems -

In [ ]:
#Q.23] Self Product of an array w/o the respective positioned number -

nums = [2,3,4,5,6]
def productexceptself(nums):
    res = [1]*(len(nums))
    prefix=1
    for i in range(len(nums)):
        res[i]=prefix
        prefix*=nums[i]
    postfix=1
    for i in range(len(nums)-1,-1,-1): #?
        res[i]*=postfix
        postfix*=nums[i]
    return res
prod = productexceptself(nums)
prod

[360, 240, 180, 144, 120]

In [ ]:
# Q.24] Find contiguous subarray(min 1 number) having largest sum & return it
# - Brute Force => just compute every single subarray from start to end. Repeat for every number following on. But time complexty very very high
# - Solution -
# - prev lesser value doesn't matter. Thus ignore. Calculate max sum upto a number where the number is decreasing the max sum value.
# Calculate such max values and return.

nums = [-5,-6,-10,0,3,65,2,8,22,3,4,5,6,-3,-6,4,2,0,-1]
def contiguoussubarray(nums):
    maxsub = nums[0]
    cursum = 0
    for n in nums:
        if cursum < 0:
            cursum = 0
        cursum+=n
        maxsub=max(maxsub,cursum)
    return maxsub
prod = contiguoussubarray(nums)
prod

118

In [ ]:
#Q.25] Maximum Product Subarray - Dynamic Programming - *** Revisit lsater *****

nums = [2,3,4,5,6,-6,-4,0,-4,5,6,-7,0,-5,-2,2]
def contiguoussubarrayprod(nums):
    res=max(nums) # coz when array has 0 Or -1, res becomes invalid.
    currmin,currmax=1,1
    for n in nums:
        if n==0:
            currmin,currmax=1
            continue
        tmp=n*currmax # to keep track of what currmax is and what currmin is
        currmax = max(n*currmax,n*currmin,n)
        currmin = min(tmp,n*currmin,n)
        res=max(res,currmax)
    return res
prod = contiguoussubarrayprod(nums)
prod

TypeError: ignored

In [ ]:
#Q.26] Pythagorean -
def hasPythagoreanTriplet(nums):
    squared_nums = set([num * num for num in nums])  # Create a set of squared values
    for i in range(len(nums)):
        for j in range(i + 1, len(nums)):
            # Calculate the sum of squares of two numbers
            sum_of_squares = nums[i] * nums[i] + nums[j] * nums[j]
            if sum_of_squares in squared_nums:
                return True
    return False
input_nums = [3, 5, 5, 6, 13, 9,12]
result = hasPythagoreanTriplet(input_nums)
print(result)  # Output: True

True


In [ ]:
#Q.27] # Denominations & Amount - Dynamic Programming
denominations = [1,2,5]
amount = 5
solution = [0] * (amount + 1)
solution[0] = 1
for den in denominations:
    for i in range(den, amount + 1): #1 to 6? -- 1-5
        #print(i)
        solution[i] += solution[i - den]
        print(solution)
print(solution[len(solution) - 1])

[1, 1, 0, 0, 0, 0]
[1, 1, 1, 0, 0, 0]
[1, 1, 1, 1, 0, 0]
[1, 1, 1, 1, 1, 0]
[1, 1, 1, 1, 1, 1]
[1, 1, 2, 1, 1, 1]
[1, 1, 2, 2, 1, 1]
[1, 1, 2, 2, 3, 1]
[1, 1, 2, 2, 3, 3]
[1, 1, 2, 2, 3, 4]
4


In [ ]:
#Q.28] # Missing element in a continuos array
list1 = [1,5,6,3,4]
def findmissing(list1):
    currsum = sum(list1) #19
    correctsum = ((len(list1)+1)*(len(list1)+2))/2 # 6*7/2=21
    return correctsum-currsum
findmissing(list1)

2.0

In [ ]:
#Q.29]  Given an array, find the maximum difference in both their consecutive values & their index -
# myarr = [4,6,3,4,7,2,233,64,56,77,22,0,86,54]
myarr = [5, 70, 40, 50, 12, 38, 98]
lambai = len(myarr)
maxdiff = 0
for i in range(1,len(myarr)):
#     maxdiff = max(maxdiff,myarr[i]-myarr[i-1]
      if maxdiff < myarr[i]-myarr[i-1]:
        maxdiff = myarr[i]-myarr[i-1]
        jmax = i
        imax = i-1
print("Maxdiff - ",maxdiff)
print("Max j - ",jmax)
print("Max i - ",imax)

Maxdiff -  65
Max j -  1
Max i -  0


In [ ]:
#Q.30] Maximum difference max(j – i) such that arr[j] > arr[i]-

myarr = [4,6,3,4,7,2,233,64,56,77,22,0,86]
n = len(myarr) # 13
left_min = [0] * n
left_min[0] = myarr[0]
for i in range(1, n):
    left_min[i] = min(left_min[i - 1], myarr[i])

right_max = [0]*n
right_max[n-1] = myarr[n-1]
for i in range(n-2,-1,-1):
    right_max[i] = max(right_max[i+1],myarr[i])

i, j, max_diff = 0, 0, -1
while i < n and j < n:
    if left_min[i] < right_max[j]:
        max_diff = max(max_diff, j - i)
        j += 1
    else:
        i += 1
print(i,j,max_diff)

0 13 12


In [ ]:
#Q.31]

def max_index_diff(array):
    n = len(array)
    max_diff = 0
    for i in range(0, n):
        j = n - 1
        while(j > i):
            if array[j] > array[i] and max_diff < (j - i):
                max_diff = j - i
            j -= 1
    return max_diff
max_index_diff(myarr)

12

In [ ]:
#Q.32] #the longest consecutive subsequence in a list of numbers.
def longest_consecutive_subsequence(nums):
    if not nums:
        return []
    nums = sorted(set(nums))
    longest_streak = []
    current_streak = [nums[0]]
    for i in range(1, len(nums)):
        if nums[i] - nums[i - 1] == 1:
            current_streak.append(nums[i])
        else:
            if len(current_streak) > len(longest_streak):
                longest_streak = current_streak
            current_streak = [nums[i]]

    return longest_streak if len(longest_streak) > len(current_streak) else current_streak

numbers = [1, 2, 3, 5, 6, 7, 8, 10]
print(longest_consecutive_subsequence(numbers))

[5, 6, 7, 8]


In [31]:
#Q.33] Write a function that finds the longest common subsequence (LCS) of two strings - Dynamic Programming

def lcs(X, Y):
    m = len(X) #7
    n = len(Y)   #5
    dp = [[None] * (n + 1) for i in range(m + 1)]

    for i in range(m + 1):
        for j in range(n + 1):
            if i == 0 or j == 0:
                dp[i][j] = 0
            elif X[i-1] == Y[j-1]:
                dp[i][j] = dp[i-1][j-1] + 1
            else:
                dp[i][j] = max(dp[i-1][j], dp[i][j-1])
    return dp[m][n]

str1 = "ABCBDAB"
str2 = "BDCAB"
print(lcs(str1, str2))

4


In [32]:
#Q.34]  Write a function that computes the power of a number without using the built-in power function or the ** operator

def power(base, exp):
    if exp == 0:
        return 1
    if exp < 0:
        base = 1 / base
        exp = -exp

    result = 1
    current_product = base
    while exp > 0:
        if exp % 2 == 1:
            result = result * current_product
        current_product = current_product * current_product
        exp //= 2
    return result

print(power(2, 3))  # Output: 8
print(power(3, -2)) # Output: 0.1111 (or close to it)

8
0.1111111111111111


In [34]:
#Q.35] Write a function that returns the longest substring without repeating characters

def length_of_longest_substring(s):
    n = len(s)
    ans = 0
    char_index = {}  # Current index of character
    i = 0  # The sliding window left pointer
    for j in range(n):
        if s[j] in char_index: #char value of the string
            i = max(char_index[s[j]], i)# this is index
            print(char_index[s[j]])
        ans = max(ans, j - i + 1)
        char_index[s[j]] = j + 1
    return ans

print(length_of_longest_substring("abcabcbb"))

1
2
3
5
7
3


In [38]:
#Q.36] Given a non-empty string s and a dictionary wordDict containing a list of non-empty words, determine if s can be segmented into a space-separated
# sequence of one or more dictionary words.

def word_break(s, wordDict):
    wordSet, n = set(wordDict), len(s)
    dp = [False] * (n + 1)
    dp[0] = True

    for i in range(1, n + 1):
        for j in range(i):
            if dp[j] and s[j:i] in wordSet:
                dp[i] = True
                break
    return dp[-1]

s = "leetcode"
wordDict = ["leet", "code"]
print(word_break(s, wordDict))

True
